from __future__ import annotations

import office_mcp.tools.powerpoint as powerpoint_tools


def test_powerpoint_table_helpers_are_imported() -> None:
    required_helpers = [
        "_add_chart",
        "_change_chart_type",
        "_clear_animations",
        "_copy_animation",
        "_copy_to_clipboard",
        "_export_html",
        "_export_images",
        "_format_chart",
        "_format_chart_axis",
        "_get_chart_data",
        "_get_slide_preview",
        "_get_slideshow_status",
        "_list_animations",
        "_ppt_get_table_cells",
        "_ppt_clear_placeholder",
        "_ppt_extract_text_as_markdown",
        "_ppt_format_text_range",
        "_ppt_find_replace_text",
        "_ppt_get_text",
        "_ppt_get_placeholder",
        "_ppt_get_placeholder_type",
        "_ppt_set_table_cells",
        "_ppt_batch_set_table_data",
        "_ppt_get_textframe",
        "_ppt_list_placeholders",
        "_ppt_merge_table_cells",
        "_ppt_resize_placeholder",
        "_ppt_split_table_cells",
        "_ppt_set_paragraph_format",
        "_ppt_add_table_row",
        "_ppt_delete_table_row",
        "_ppt_add_table_column",
        "_ppt_delete_table_column",
        "_ppt_set_bullets",
        "_ppt_set_fill",
        "_ppt_set_font_color",
        "_ppt_set_font_size",
        "_ppt_set_line",
        "_ppt_set_placeholder",
        "_ppt_set_shadow",
        "_ppt_set_text",
        "_ppt_set_table_style",
        "_ppt_set_table_borders",
        "_ppt_get_table_info",
        "_ppt_resize_table",
        "_set_chart_data",
        "_set_chart_series",
        "_set_animation_trigger",
        "_slideshow_goto",
        "_slideshow_next",
        "_slideshow_previous",
        "_start_slideshow",
        "_stop_slideshow",
        "_ungroup_ppt_shapes",
        "_update_animation",
        "_remove_animation",
    ]

    for helper_name in required_helpers:
        assert hasattr(powerpoint_tools, helper_name), helper_name
